-- mostrar databases (mesma coisa que o show databases no mysql)
\l

-- criar database
CREATE DATABASE perguntas;

-- utilizar database (mesma coisa que o use no mysql)
\c database_name

-- criar tabela
CREATE TABLE perguntas_table (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  descricao TEXT NOT NULL
);

-- mostrar tabela (mesma coisa que o desc no mysql)
\d perguntas;


-- mostrar dados da tabela
SELECT * FROM perguntas_table;
